### ISSUE TITLE
It says Inconsistent Indentaion Detected

### ISSUE THREAD

**Issue by ghost** [acini/autowikibot-py#11]
It says Inconsistent Indentaion Detected and I can't start it please help!!

**Comment by acini** [comment]
What line number does it traceback to? I am not getting any error with current git clone.

**Comment by ghost** [comment]
I am very new to this by the way. It's not a syntax error, and it doesn't trace back to a specific line. It just sayd Inconsistent Indentation Deteted. What version of python are you using? Are you on windows or linux? If linux which one? Can you tell me a little? :)

**Comment by acini** [comment]
It should work perfectly with python 2.7.3 (GNU/Linux Debian Wheezy). You can run the script via terminal. While running on linux, it will exit with error message pointing to where the indentation is bad, for example:

```
  File "a", line 8
    log("DONE")
       ^
IndentationError: expected an indented block
```

---

Also make sure you have dependency files ready. 
**Like this:**

`already_done_dump` - Create empty file if running for first time.

`totalposted` - Create empty file if running for first time.

`badsubs` - Create empty file if running for first time. Add excluded subreddits if you are using \"all\" as allowed subreddit. Leave empty if allowing specific subreddits.

`banned_users` - Create empty file if running for first time. Bot will add banned users automatically. Add manually on separate lines.

`imgur_client_id` - Put your imgur client_id in that file

`userpass` - a file with username on first line and password on second

**Comment by ghost** [comment]
Ok thanks

**Comment by ghost** [comment]
Ok, so my folder looks like this:
![wiki](https://f.cloud.github.com/assets/1896630/1984953/9c0ef552-8435-11e3-92d9-294354b3cac0.PNG)
I have my username and password, and my imgur client_id what now? Do I start IDLE and open the commenter? To be fair, you have no real setup instructions.

**Comment by acini** [comment]
These files have .txt extension.

Go to folder options, untick hide known extensions and remove .txt from names of files.

I haven't written any instructions because the bot is pretty easy to deploy by someone who has basic programming knowledge. I would personally recommend that you start using some flavour of GNU/Linux and try practicing in python shell.

**Comment by ghost** [comment]
Ok I fixed it but you dont have a (underscore)(underscore)MAIN(underscore)(underscore) module dude.. I wrote (underscore) instead of "_" because github uses underscores as bold

**Comment by acini** [comment]
Yeah, needn't have __main__; because commenter has no functions or classes that can be reused somewhere else.

> https://github.com/acini/autowikibot-py/issues/16#issuecomment-33343198

It is running on debian wheezy with python 2.7.3 with libraries mentioned in README.md installed. That's it. If you need help setting up a mirror bot on private sub or something, I can assist you via SSH/RDP/TeamViewer, PM me the access credentials on my reddit account /u/acini.
