### ISSUE TITLE
Style Guide Proposal and Code Refactoring

### ISSUE THREAD

**Issue by bmallin** [acini/autowikibot-py#39]
I am proposing the adoption of a style guide for all contributed code. Of course, for general code style I would recommend [PEP 8](http://legacy.python.org/dev/peps/pep-0008/), which tends to be the defacto standard for python code.

In addition to adopting a style guide, I propose that the current code base be refactored to follow the adopted style guidelines.

Also, in it's current state, the code is pretty much entirely undocumented, which makes it very difficult for others to contribute bux fixes and general enhancements to the project. I would like to see at the very least module docstrings for every file and function docstrings for every function.

I believe that these changes will make the project much more approachable for new contributors and help foster a community around this awesome project.

Thoughts? Comments? Criticisms?

**Comment by acini** [comment]
I agree. I was going to do this along with #29, where bot would have separate queue for fetched comments which would pass through definitive response filter to the process queue. I also planned to modify code for Python 3 standards during the same change and create a ruby fork for efficiency testing.

I am currently too busy to get into recoding it due to academic reasons. You are welcome send pull requests.
